openapi: 3.2.0
info:
  version: 0.0.0
  description: 'This page documents the operations supported by the PassiveLogic HTTP API, covering authentication,
    user management, and

    GraphQL API access.'
  title: PassiveLogic REST Tunnel API
tags:
- name: tunnel
paths:
  /api/v0.20/tunnel/{serialNumber}/**:
    put:
      tags:
      - tunnel
      description: PUT /tunnel/:serialNumber/**
      security:
      - Basic Auth - login: []
      - XSRF header: []
      - DEPRECATED - PL API Key: []
      - PL API Key: []
    delete:
      tags:
      - tunnel
      description: DELETE /tunnel/:serialNumber/**
      security:
      - Basic Auth - login: []
      - XSRF header: []
      - DEPRECATED - PL API Key: []
      - PL API Key: []
    post:
      tags:
      - tunnel
      description: POST /tunnel/:serialNumber/**
      security:
      - Basic Auth - login: []
      - XSRF header: []
      - DEPRECATED - PL API Key: []
      - PL API Key: []
    get:
      tags:
      - tunnel
      description: GET /tunnel/:serialNumber/**
      security:
      - Basic Auth - login: []
      - XSRF header: []
      - DEPRECATED - PL API Key: []
      - PL API Key: []
  /api/tunnel/{serialNumber}/**:
    delete:
      tags:
      - tunnel
      description: DELETE /tunnel/:serialNumber/**
      security:
      - Basic Auth - login: []
      - XSRF header: []
      - DEPRECATED - PL API Key: []
      - PL API Key: []
    put:
      tags:
      - tunnel
      description: PUT /tunnel/:serialNumber/**
      security:
      - Basic Auth - login: []
      - XSRF header: []
      - DEPRECATED - PL API Key: []
      - PL API Key: []
    post:
      tags:
      - tunnel
      description: POST /tunnel/:serialNumber/**
      security:
      - Basic Auth - login: []
      - XSRF header: []
      - DEPRECATED - PL API Key: []
      - PL API Key: []
    get:
      tags:
      - tunnel
      description: GET /tunnel/:serialNumber/**
      security:
      - Basic Auth - login: []
      - XSRF header: []
      - DEPRECATED - PL API Key: []
      - PL API Key: []
components:
  securitySchemes:
    XSRF_header:
      in: header
      description: Authentication using an XSRF protected JWT
      name: X-PL-AUTH
      type: apiKey
    Basic_Auth_-_login:
      description: Basic authentication used only at login.
      scheme: basic
      type: http
    PL_API_Key:
      in: header
      description: PL API Key in header
      name: PL-API-KEY
      type: apiKey
    DEPRECATED_-_PL_API_Key:
      in: header
      description: DEPRECATED - PL API Key in Bearer header
      name: 'Authorization: PL-API-KEY'
      type: apiKey
